routes/web.php
<?php

/**
 * The Home Page
 */
Route::get('/', 'PagesController@home');

/**
 * Notices
 */
Route::resource('notices', 'NoticesController', ['only' => [
    'index', 'create', 'store', 'update'
]]);
Route::post('/notices/confirm', 'NoticesController@confirm')->name('notices.confirm');

/**
 * Authentication
 */
Auth::routes();

// Will be replaced
Route::get('/home', 'HomeController@index')->name('home');

app/Notice.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Notice extends Model
{
	/**
	  * Fillable fields for a new notice
	  * @var array
	  */
	protected $fillable = [
		'infringing_title',
		'infringing_link',
		'original_link',
		'original_description',
		'template',
		'content_removed',
		'provider_id',
	];

	/**
	 * Open a new notice.
	 *
	 * @param array $attributes
	 * @return static
	 */
	public static function open(array $attributes)
	{
		return new static($attributes);
	}

	/**
	 * Set the emaol tempalte for the notice.
	 *
	 * @param string $template
	 * @return static
	 */
	public function useTemplate($template)
	{
		$this->template = $template;
		return $this;
	}

	/**
	 * A notice is created by a user
	 */
	public function user()
	{
		return $this->belongsTo(User::class);
	}

	/**
	 * A notice belongs to a recipient/provider.
	 */
	public function recipient()
	{
		return $this->belongsTo(Provider::class,'provider_id');
	}

	/**
	 * Get the email for the recipient of the DMCA
	 * @return string
	 */
	public function getRecipientEmail()
	{
		return $this->recipient->copyright_email;
	}
	/**
	 * Get the email address if the owner ofthe notice.
	 * @return string
	 */
	public function getOwnerEmail()
	{
		return $this->user->email;
	}
}

app/Provider.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Provider extends Model
{
	/**
	 * No timestamps for provider.
	 * 
	 * @var bool
	 */
    public $timestamps = false;

 	/**
 	 * Fillable fields for a provider.
 	 * 
 	 * @var array
 	 */
 	protected $fillable = [
 		'name',
 		'copyright_email'
 	];

}

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];
	/**
	 * A user may create many DMCA notices.
	 *
	 * @return \Illuminate\Database\Eloquent\Relation\HasMany
	 */
	public function notices()
	{
		return $this->hasMany(Notice::class);
	}
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class HomeController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('home');
    }
}

app/Http/Controllers/NoticesController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Http\Requests\{PrepareNoticeRequest};
use App\{Provider, Notice};
use Auth;
use Mail;

class NoticesController extends Controller
{
    /**
     * Create a new notices controller instance.
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
	    $notices = Auth::user()->notices()->latest()->get();
	    return view('notices.index', compact('notices'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $providers = Provider::pluck('name', 'id');

        return view('notices.create', compact('providers'));
    }

    /**
     * Validate the request before submitting
     * 
     * @param  \App\Http\Requests\PrepareNoticeRequest $request
     * @return \Illuminate\Http\Response
     */
    public function confirm(PrepareNoticeRequest $request)
    {
        $data = $request->all() + [
            'name' => auth()->user()->name,
            'email' => auth()->user()->email,
        ];
        //$template = view()->file(app_path('Http/Templates/dmca.blade.php'), $data);
        $template = view('Templates.dmca', compact('data'));
        session()->flash('dmca', $data);

        return view('notices.confirm',compact('template'));
    }



    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
	$notice = $this->createNotice($request);

	Mail::send('emails.dmca', compact('notice'), function($message)use ($notice) {
		$message->to($notice->getRecipientEmail())
			->from($notice->getOwnerEmail())
			->subject('DMCA Notice');

	});
	
	flash('Your DMCA notice has been deliverd!')->success();

	return redirect('notices');
    }


    /**
     * Create and persist a new DMCA notice.
     * @param Request
     */
    public function createNotice(Request $request)
    {
        $data = session()->get('dmca');

	$notice = Notice::open($data)->useTemplate($request->template);

	$notice = Auth::user()->notices()->save($notice);

	return $notice;
    }
    
    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Notice $notice, Request $request)
    {
	    $isRemoved = $request->has('content_removed');
	    $notice->update(['content_removed' => $isRemoved]);
	    return redirect()->back();//$notice;
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

app/Http/Controllers/PagesController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class PagesController extends Controller
{
    public function home()
    {
    	return view('pages.home');
    }
}

resources/views/Templates/dmca.blade.php
I am the copyright owner of the content, "{{ $data["infringing_title"] }}" being infringed at:

{{ $data["infringing_link"] }}

You may find the original content at:

{{ $data["original_link"] }}

{{ $data["original_description"] }}

This letter is official notification undr the provisions of Section 512(c) of the Digital Millenniym Copytight Act ("DMCA") to effect

I have ghood faith blief that the use of the material in the manner complained of is not authorized by the copytight owner, its agnto.....

Pleas send me at the addres noted below a prompt respomse indocating the actions you have taken resolve thois matter.

Sincerely,

{{ $data["name"] }}
{{ $data["email"] }}

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            <div class="panel panel-default">
                <div class="panel-heading">Dashboard</div>

                <div class="panel-body">
                    @if (session('status'))
                        <div class="alert alert-success">
                            {{ session('status') }}
                        </div>
                    @endif

                    You are logged in!
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="{{ app()->getLocale() }}">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
</head>
<body>
    <div id="app">
        @include ("layouts.nav")
	@include ('flash::message')
        <div class="container">
            @yield('content')
        </div>
    </div>
     <!--
	     <div class="flash">
		     Updated!
	     </div>
     -->
    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}"></script>
</body>
</html>

resources/views/layouts/nav.blade.php
        <nav class="navbar navbar-default navbar-static-top">
            <div class="container">
                <div class="navbar-header">

                    <!-- Collapsed Hamburger -->
                    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#app-navbar-collapse" aria-expanded="false">
                        <span class="sr-only">Toggle Navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>

                    <!-- Branding Image -->
                    <a class="navbar-brand" href="{{ url('/') }}">
                        DMCA Sender
                    </a>
                </div>

                <div class="collapse navbar-collapse" id="app-navbar-collapse">
                    <!-- Left Side Of Navbar -->
                    <ul class="nav navbar-nav">
                        &nbsp;
                        <li><a href="{{ route('notices.index') }}">Home</a></li>
                        <li><a href="{{ route('notices.create') }}">New Notice</a></li>
                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="nav navbar-nav navbar-right">
                        <!-- Authentication Links -->
                        @guest
                            <li><a href="{{ route('login') }}">Login</a></li>
                            <li><a href="{{ route('register') }}">Register</a></li>
                        @else
                            <li class="dropdown">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false" aria-haspopup="true">
                                    {{ Auth::user()->name }} <span class="caret"></span>
                                </a>

                                <ul class="dropdown-menu">
                                    <li>
                                        <a href="{{ route('logout') }}"
                                            onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                            Logout
                                        </a>

                                        <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                            {{ csrf_field() }}
                                        </form>
                                    </li>
                                </ul>
                            </li>
                        @endguest
                    </ul>
                </div>
            </div>
        </nav>

resources/views/notices/confirm.blade.php
@extends('layouts.app')

@section('content')
<h1 class="page-heading">Confirm</h1>

<form action="{{ route('notices.store') }}" method="POST">

	{{ csrf_field() }}
	<textarea name="template" cols="30" rows="20" class="form-control">{{$template}}</textarea>
	@include('errors.list')
	<br>
	<input type="submit" class="btn btn-primary btn-lg btn-block" value="Notice" name="send">
</form>
@endsection

resources/views/notices/create.blade.php
@extends('layouts.app')

@section('content')
<h1 class="page-heading">Prepare a DMCA Notice</h1>

<form action="{{ route('notices.confirm') }}" method="POST">

	{{ csrf_field() }}
	<div id="form-group">
		<label>Who are we sending this to?</label>
		<select class="selectpicker form-control" name="provider_id">
			@forelse($providers as $id => $provider_name)
				<option value="{{ $id }}">{{ $provider_name }}</option>
			@empty
				<option>There Is No Provider To Select</option>
			@endforelse
		</select>
	</div>
	<br>

	<div id="form-group">
		<label>What is the title of the content that us being infringed upon.</label>
		<input type="text" class="form-control" name="infringing_title" value="{{ old('infringing_title') }}" >
	</div>
	<br>

	<div id="form-group">
		<label>What is the link where this content is located.</label>
		<input type="text" class="form-control" name="infringing_link" value="{{ old('infringing_link') }}" >
	</div>
	<br>

	<div id="form-group">
		<label>To verify that you own the content, we now need the link to the original content on your server.</label>
		<input type="text" class="form-control" name="original_link" value="{{ old('original_link') }}" >
	</div>
	<br>

	<div id="form-group">
		<label>And, finally, it might help to provide some extra information related to this DMCA notice.</label>
		<textarea name="original_description" cols="30" rows="5" class="form-control">{{ old('original_description') }}</textarea>
	</div>
	<br>

	@include('errors.list')

	<input type="submit" class="btn btn-primary btn-lg btn-block" value="Preview Notice" name="send">
</form>
@endsection

resources/views/notices/index.blade.php
@extends('layouts.app')

@section('content')
<h1 class="page-heading">Your Notices</h1>
<table class="table table-striped table-borderd">
	<thead>
		<th>This Content:</th>
		<th>Accessible Here:</th>
		<th>Is Infringing Upon My Work Here:</th>
		<th>Notice Sent:</th>
		<th>Content Removed:</th>
	</thead>
	<tbody>
	@foreach ($notices->where('content_removed', false) as $notice)
	<tr>
		<td>{{ $notice->infringing_title }}</td>
		<td><a href="{{ $notice->infringing_link }}">{{ $notice->infringing_link }}</a></td>
		<td><a href="{{ $notice->original_link}}">{{ $notice->original_link}}</a></td>
		<td><a href="#">{{ $notice->created_at->diffForHumans() }}</a></td>
		<td>
			<form action="{{ route("notices.update", $notice->id) }}" method="post">
				{{ method_field('PATCH') }}
				{{ csrf_field() }}
				<input type="checkbox" name="content_removed" id="" value="{{ $notice->content_removed }}" {{ $notice->content_removed ? "checked":"" }}/>
				<button id="" type="submit">x</button>
			</form>
		</td>
	</tr>
	@endforeach
	</tbody>
</table>
@unless($notices->where('content_removed', false)->count())
	<p class="text-center">You haven't sent any DMCA notices yet!</p>
@endunless
<br><hr><br>
@if ($notices->where('content_removed', true)->count())
<h1 class="page-heading">Archived Notices</h1>
<table class="table table-striped table-borderd">
	<thead>
		<th>This Content:</th>
		<th>Accessible Here:</th>
		<th>Is Infringing Upon My Work Here:</th>
		<th>Notice Sent:</th>
		<th>Content Removed:</th>
	</thead>

	<tbody>
	@foreach ($notices->where('content_removed', true) as $notice)
	<tr>
		<td>{{ $notice->infringing_title }}</td>
		<td><a href="{{ $notice->infringing_link }}">{{ $notice->infringing_link }}</a></td>
		<td><a href="{{ $notice->original_link}}">{{ $notice->original_link}}</a></td>
		<td><a href="#">{{ $notice->created_at->diffForHumans() }}</a></td>
		<td>
			<form action="{{ route("notices.update", $notice->id) }}" method="post">
				{{ method_field('PATCH') }}
				{{ csrf_field() }}
				<input type="checkbox" name="content_removed" id="" value="{{ $notice->content_removed }}" {{ $notice->content_removed ? "checked":"" }}/>
				<button id="" type="submit">x</button>
			</form>
		</td>
	</tr>
	@endforeach
	</tbody>
</table>
@endif
@endsection

resources/views/pages/home.blade.php
@extends('layouts.app')

@section('content')
Home Page
@endsection